# -*- coding: utf-8 -*-
"""Massive Employee  app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bCAOf8iMK5D-LIdP-O0TInhLo9ijaj-z

**Data cleaning Manually**
"""

df.shape

df.info()

df.describe()

"""**Finding Missing Values:**"""

df.isnull().sum()

"""**Handle Missing Values:**"""

df['Department'].unique()

df['Department'] = df['Department'].fillna('Unknown')

"""**Email**"""

df['Email'].isnull().sum()

"""**Replace**"""

df['Email'] = df['Email'].fillna('Not Available')

"""**Replace missing city:**"""

df['City'] = df['City'].fillna('Unknown')

"""**Finding Duplicate Rows**

**Check Duplicates:**
"""

df.duplicated().sum()

"""**Display Duplicates:**"""

df[df.duplicated()]

"""**Remove duplicates:**"""

df = df.drop_duplicates()

"""**Verify:**"""

df.duplicated().sum()

"""**Clean Text Formatting:**"""

df['City'].unique()

df['City'] = df['City'].str.strip()
df['City'] = df['City'].str.title()

df['City'].unique()

"""**Standardize Department Names**"""

df['Department'].unique()

df['Department'] = df['Department'].replace({'hr':'HR','it':'IT','FINANCE':'Finance'})

df['Department'].unique()

"""**Clean Employee Names**"""

df['Name'].head(20)

df['Name'] = df['Name'].str.strip()
df['Name'] = df['Name'].str.title()

"""**Detect Age Outliers**"""

df['Age'].describe()

df[df['Age']> 100]

df = df[(df['Age'] >= 18) & (df['Age'] <= 60)]

df['Age'].describe()

"""**Detect Salary Outliers**"""

df['Salary'].describe()

df[df['Salary'] > 200000]

df = df[df['Salary'] <= 200000]

"""**Fixing Invalid Dates**"""

df['JoinDate'] = pd.to_datetime(df['JoinDate'],errors='coerce')

df['JoinDate'].isnull().sum()

df = df.dropna(subset=['JoinDate'])

"""**Checking Employee ID Duplicates**"""

df['EmployeeID'].duplicated().sum()

df[df['EmployeeID'].duplicated()]

df = df.drop_duplicates(subset='EmployeeID',keep='first')

"""**FINAL CHECK**"""

df.info()

df.isnull().sum()

df.duplicated().sum()

"""**Save Cleaned Dataset**"""

df.to_csv('Cleaned_Employee_Dataset.csv',index=False)

from google.colab import files
files.download('Cleaned_Employee_Dataset.csv')

"""**Data Cleaning Automatically**"""

import pandas as pd
import numpy as np

df = pd.read_excel('/content/drive/MyDrive/Messy_Employee_Dataset_1280Rows.xlsx')
print("Original Shape:", df.shape)

df['Department'] = df['Department'].fillna('Unknown')
df['Email'] = df['Email'].fillna('Not Available')
df['City'] = df['City'].fillna('Unknownn')
print("Departments after Cleaning:")
print(df['Department'].unique())
print("Emails after Cleaning:")
print(df['Email'].unique())
print("Cities after Cleaning:")
print(df['City'].unique())

df['Name'] = df['Name'].str.strip().str.title()
df['City'] = df['City'].str.strip().str.title()

df['Department'] = df['Department'].replace({'hr': 'HR', 'it': 'IT', 'FINANCE': 'Finance'})

df = df.drop_duplicates()
print("Duplicate Rows After Removal:")
print(df.duplicated().sum())
print("Current Shape:", df.shape)

df['JoinDate'] = pd.to_datetime(df['JoinDate'], errors='coerce')
print("Invalid Dates Found:")
print(df['JoinDate'].isnull().sum())

df = df.dropna(subset=['JoinDate'])
print("Shape After Date Claening:")
print(df.shape)

df = df[(df['Age'] >= 18) & (df['Age'] <= 60)]
df = df[df['Salary'] <= 200000]
print("Salary After Cleaning:")
print(df['Salary'].describe())

df = df.drop_duplicates(subset='EmployeeID', keep='first')

print("\nCleaned Shape:", df.shape)
print("\nMissing Values:")
print(df.isnull().sum())
print("\nDuplicate Rows:", df.duplicated().sum())

output_file = 'Cleaned_Employee_Dataset.csv'
df.to_csv(output_file, index=False)
print("\nCleaned dataset saved to:", output_file)

from google.colab import files
files.download('Cleaned_Employee_Dataset.csv')

print("----- DATA CLEANING REPORT -----")
print("Rows after cleaning:", len(df))
print("Columns:", len(df.columns))
print("Missing Values:", df.isnull().sum().sum())
print("Duplicate Rows:", df.duplicated().sum())
print("Duplicate Employee IDs:",
      df['EmployeeID'].duplicated().sum())

"""**10 Business Questions And Answers**

**Q1: Which departments have the highest total salary expenditure?**

Business Value: Helps HR and management identify departments with the highest workforce costs.
"""

dept_salary = df.groupby('Department').agg(Total_Salary=('Salary','sum')).reset_index()
print(dept_salary.sort_values(by='Total_Salary', ascending=False))

"""**Q2: Which cities have the highest number of employees?**

Business Value: Helps management understand workforce distribution across locations.
"""

city_emp = df.groupby('City').agg( Employee_Count=('EmployeeID','count')).reset_index()
print(city_emp.sort_values(by='Employee_Count', ascending=False))

"""**Q3: What is the average salary by department?**

Business Value: Supports salary benchmarking and compensation planning.
"""

avg_salary = df.groupby('Department').agg(Average_Salary=('Salary','mean')).reset_index()
print(avg_salary.sort_values(by='Average_Salary', ascending=False))

"""**Q4: Which department has the youngest workforce?**

Business Value: Helps identify departments with early-career talent.
"""

young_dept = df.groupby('Department').agg(Average_Age=('Age','mean')).reset_index()
print(young_dept.sort_values(by='Average_Age'))

"""**Q5: Which department has the oldest workforce?**

Business Value: Helps succession planning and retirement forecasting.
"""

old_dept = df.groupby('Department').agg(Average_Age=('Age','mean')).reset_index()
print(old_dept.sort_values(by='Average_Age', ascending=False))

"""**Q6: Which city contributes the highest salary cost?**

Business Value: Helps evaluate location-based operational expenses.
"""

city_salary = df.groupby('City').agg(Total_Salary=('Salary','sum')).reset_index()
print(city_salary.sort_values(by='Total_Salary', ascending=False))

"""**Q7: How many employees joined each year?**

Business Value: Tracks hiring trends over time.
"""

df['Join_Year'] = pd.to_datetime(df['JoinDate']).dt.year
join_year = df.groupby('Join_Year').agg(Employees_Joined=('EmployeeID','count')).reset_index()
print(join_year)

"""**Q8: Which department has the highest employee count?**

Business Value: Identifies departments with the largest workforce.
"""

dept_count = df.groupby('Department').agg(Employee_Count=('EmployeeID','count')).reset_index()
print(dept_count.sort_values(by='Employee_Count', ascending=False))

"""**Q9: What are the top 10 highest-paid employees?**

Business Value: Helps identify salary concentration and compensation trends.
"""

top_paid = df[['EmployeeID','Name','Department','Salary']]
print(top_paid.sort_values(by='Salary', ascending=False).head(10))

"""**Q10: Which city has the highest average salary?**

Business Value: Supports location-based compensation analysis.
"""

city_avg_salary = df.groupby('City').agg(Average_Salary=('Salary','mean')).reset_index()
print(city_avg_salary.sort_values(by='Average_Salary', ascending=False))

df_cleaned = pd.read_csv('Cleaned_Employee_Dataset.csv')
df_cleaned.head()

"""Matplotlib"""

import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/Messy_Employee_Dataset_1280Rows.xlsx')
df
import matplotlib.pyplot as plt
city_salary = df.groupby('City').agg(Total_Salary=('Salary','sum')).reset_index()
print(city_salary.sort_values(by='Total_Salary', ascending=False))
plt.figure(figsize=(8,5))
plt.plot(city_salary['City'],
         city_salary['Total_Salary'],
         marker='o')
plt.title('Total Salary by City')
plt.xlabel('City')
plt.ylabel('Total Salary')
plt.grid(True)
plt.show()

mcity_dept = df.groupby(['City', 'Department']).size().unstack(fill_value=0)
plt.figure(figsize=(10,6))
plt.plot(city_dept.index, city_dept['HR'],
         marker='o', label='HR')
plt.plot(city_dept.index, city_dept['IT'],
         marker='s', label='IT')
plt.plot(city_dept.index, city_dept['Finance'],
         marker='^', label='Finance')
plt.plot(city_dept.index, city_dept['Sales'],
         marker='d', label='Sales')
plt.title('Employee Count by City and Department')
plt.xlabel('City')
plt.ylabel('Number of Employees')
plt.legend()
plt.grid(True)

plt.show()

"""Employee ID Vs Salary"""

plt.figure(figsize=(10,6))
plt.scatter(df['EmployeeID'], df['Salary'])
plt.title('Employee ID vs Salary')
plt.xlabel('Employee ID')
plt.ylabel('Salary')
plt.grid(True)
plt.show()

"""**Employee Distribution by City**"""

city_count = df['City'].value_counts()
plt.figure(figsize=(8,8))
plt.pie(city_count, labels=city_count.index,
        autopct='%1.1f%%')
plt.title('Employee Distribution by City')
plt.show()

"""**Employee Count by City**"""

city_count = df['City'].value_counts()
plt.figure(figsize=(8,5))
plt.bar(city_count.index, city_count.values)
plt.title('Employee Count by City')
plt.xlabel('City')
plt.ylabel('Number of Employees')
plt.grid(True)
plt.show()

"""**Age distribution**"""

plt.figure(figsize=(8,5))
plt.hist(df['Age'], bins=8)
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('number of Employees')
plt.grid(True)
plt.show()

"""**Subplot**"""

plt.figure(figsize=(12,6))
plt.subplot(1,2,1)
plt.bar(df['EmployeeID'], df['Salary'])
plt.title('Employee ID')
plt.xticks(rotation=90)

plt.subplot(1,2,2)
city_count = df['City'].value_counts()
plt.bar(city_count.index, city_count.values)
plt.title('Employee Count by City')
plt.xticks(rotation=90)

plt.tight_layout()
plt.xlabel('City')
plt.ylabel('Number of Employees')
plt.tight_layout()
plt.show()

"""**Seaborn**"""

import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(style="darkgrid", palette="cool")
sns.barplot(
    data=df,
    x='City',
    y='Salary',

)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(style="darkgrid", palette="rocket")
sns.barplot(
    data=df,
    x='City',
    y='Salary',

)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(style="darkgrid", palette="crest")
sns.barplot(
    data=df,
    x='City',
    y='Salary',

)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(style="darkgrid", palette="Spectral")
sns.barplot(
    data=df,
    x='City',
    y='Salary',

)
plt.show()

"""**Heatmap**"""

plt.figure(figsize=(12, 8))
df_dummies = pd.get_dummies(df, columns=['Department'], prefix='Department', dtype=int)
selected_correlation_cols = ['Age', 'Salary'] + \
                            [col for col in df_dummies.columns if col.startswith('Department_') \
                             and col.replace('Department_', '') in ['IT', 'HR', 'Finance', 'Unknown']]
corr_matrix = df_dummies[selected_correlation_cols].corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=1)
plt.title('Correlation Heatmap including Department Dummies')
plt.show()

